### ISSUE TITLE
Getting "No project is available for evaluation" error when debugging web app using mvn jetty:run

### ISSUE THREAD

**Issue by qianwch** [dansomething/coc-java-debug#37]
**Describe the issue**
Could not evaluate variables when debugging web apps using mvnDebug jetty:run, But it is ok when using mvnDebug tomcat7:run.

**To Reproduce**
1. Open the sample project.
2. run mvnDebug jetty:run
3. run "CocCommand java.debug.vimspector.start", to open the debugger
4. Set breakpoint in the NoFoundServlet class.
5. run curl http://localhost:8080/demo-app-1/fdsfasdfdsa
6. Go to debug-view, try to evaluate variables,will get error: Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..

In step 2, if I use mvnDebug tomcat7:run to launch, there will be no problem.
I have compared the vimspector debug log, and find nothing different between jetty:run and tomcat7:run.

**Expected behavior**
The variable evaluation function as expected.

**Versions of relevant software**
 - vim: 8.2.3455 (172)
 - coc.nvim: latest
 - coc-java: latest
 - vimspector: latest
 - java: both java8 and java11
 - maven: 3.8.1

**Relevant logs and error messages**
* View the trace logging output for the Java language server:
    * Set `{ "java.trace.server": "verbose" }` in `:CocSettings`.
    * Run the command `:CocCommand workspace.showOutput java`.
    * Are there any errors?
    !MESSAGE [error response][evaluate]: Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
!STACK 0
com.microsoft.java.debug.core.DebugException: Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
	at com.microsoft.java.debug.core.adapter.AdapterUtils.createCompletionException(AdapterUtils.java:257)
	at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:147)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json.
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.findJavaProjectByType(JdtEvaluationProvider.java:277)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.ensureDebugTarget(JdtEvaluationProvider.java:405)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:140)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.evaluate(JdtEvaluationProvider.java:115)
	at com.microsoft.java.debug.core.adapter.handler.EvaluateRequestHandler.lambda$handle$0(EvaluateRequestHandler.java:84)
	... 7 more
* View the Vimspector log `:VimspectorShowOutput Vimspector`.
    * Are the any errors?
* After running the command `:CocCommand java.debug.vimspector.start` Do you see a message like `[coc.nvim] Java debug server started on port` in the output of `:messages`?
Cannot evaluate because of java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json..
**Additional context**

**Screenshots**
It is fine with tomcat7:run
<img width="1030" alt="2022-06-01 18 55 37" src="https://user-images.githubusercontent.com/45196316/171388937-d25e8b26-952c-455f-ae47-786508cc8aa6.png">
It does not work with jetty:run
<img width="1082" alt="2022-06-01 18 56 18" src="https://user-images.githubusercontent.com/45196316/171388952-d699e990-a75e-4524-8790-5860b5689112.png">
The sample project:
[demo-app-1.tar.gz](https://github.com/dansomething/coc-java-debug/files/8813442/demo-app-1.tar.gz)

**Comment by qianwch** [comment]
It seems like a env problem, I have tested in another computer, it is all ok.
It could be a problem of maven 3.8.1.
